# Generated by Django 5.0.6 on 2024-11-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
